# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.aero_sections = QtWidgets.QTabWidget(self.centralwidget)
        self.aero_sections.setEnabled(True)
        self.aero_sections.setObjectName("aero_sections")
        self.gridLayout.addWidget(self.aero_sections, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_section_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_section_button.setObjectName("add_section_button")
        self.horizontalLayout.addWidget(self.add_section_button)
        self.delete_section_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_section_button.setObjectName("delete_section_button")
        self.horizontalLayout.addWidget(self.delete_section_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.build_button = QtWidgets.QPushButton(self.centralwidget)
        self.build_button.setObjectName("build_button")
        self.horizontalLayout.addWidget(self.build_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.aero_sections.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "xflr5_to_xrotor"))
        self.add_section_button.setText(_translate("MainWindow", "Add"))
        self.delete_section_button.setText(_translate("MainWindow", "delete"))
        self.build_button.setText(_translate("MainWindow", "Build"))
